general:
  branches:
    only:
      - develop
      - feature/
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

language: java
jdk:
  - oraclejdk8

install:
  # TODO: properly make maven profiles to skip gpg by default.
  - mvn install -DskipTests=true -Dgpg.skip=true -B -V
script:
  - mvn test -B

before_deploy:
  - bash ./target/pages.bash
deploy:
  provider: pages
  local_dir: ./target/gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  on:
    branch: develop
